name: Owntest
on:
    push:
        branches: [main]
jobs:
    build:

        name: Build my virtual OS

        runs-on: ubuntu-latest

        steps:

        - name: checkout my codes
          uses: actions/checkout@v2

        - name: Print and list out content
          run: |
            ls
            echo Hello There!

        - name: Checkout repo
          uses: actions/checkout@v2
          with:
            repository: jh3406/manualtest
            #path: <folder of choice>
            #token: ${{ secrets.SEC_TOKEN }}

        - name: install pytest
          run: |
            pip3 install pytest

        - name: Run test
          run: |
            pytest test_calculator.py --junit-xml=test-results.xml
            cat README.md

        - name: List content
          run: |
            ls
            pwd

        - name: Publish Test Results
          uses: EnricoMi/publish-unit-test-result-action/composite@v2
          if: always()
          with:
            junit_files: "test-results.xml"

        - name: create folder
          run: mkdir downloads
          
      
        - name: move files
          run: mv *.xml ./downloads
            
        - name: Upload document
          uses: actions/upload-artifact@v2
          with: 
              name: assetDocuments
              path: downloads

        