name: Start
on:
    push:
        branches: [main]
jobs:
    build:

        name: Build my virtual OS

        runs-on: ubuntu-latest

        steps:

        - name: checkout my codes
          uses: actions/checkout@v2

        - name: Print and list out content
          run: |
            ls
            echo Hello There!

        - name: Checkout repo remotely
          uses: actions/checkout@v2
          with:
            repository: jh3406/manualtest
            #path: <folder of choice>
            #token: ${{ secrets.SEC_TOKEN }}

        - name: install pytest
          run: |
            pip3 install pytest

        - name: Run test
          run: |
            pytest test_calculator.py
            cat README.md